POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Eventos 21",
    "details": null,
    "maximumAttendees": 100,
}

###

POST http://localhost:3333/events/c6b9a31d-614c-432c-9056-7ae89cce0ea2
Content-Type: application/json

{
    "name": "Rachel",
    "email": "rachel.l.patricio@gmail.com"
}

###

GET http://localhost:3333/attendees/1/badge
Content-Type: application/json

###

GET http://localhost:3333/attendees/1/check-in
Content-Type: application/json

###

GET http://localhost:3333/events/c6b9a31d-614c-432c-9056-7ae89cce0ea2/attendees?query=leandro