POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Eventos 21",
    "details": null,
    "maximumAttendees": 100,
}

###

POST http://localhost:3333/events/c6b9a31d-614c-432c-9056-7ae89cce0ea2/attendees/
Content-Type: application/json

{
    "name": "Rachel",
    "email": "rachel.l.patricio@gmail.com"
}

###

GET http://localhost:3333/events/1fbb7cfb-797c-451f-8e23-afed266a3b7d
Content-Type: application/json

###

GET http://localhost:3333/events/1fbb7cfb-797c-451f-8e23-afed266a3b7d/check-in
Content-Type: application/json